apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: uptime-kuma
  namespace: applications
  labels:
    app.kubernetes.io/name: uptime-kuma
spec:
  ingressClassName: nginx
  rules:
    - host: uptime-kuma.lan.hummingbirdlabs.dev
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: uptime-kuma
                port:
                  number: 80
