apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: platform-api
  namespace: applications
spec:
  interval: 10m
  releaseName: platform-api
  targetNamespace: applications
  chart:
    spec:
      chart: ./charts/spring-boot-api
      reconcileStrategy: Revision
      sourceRef:
        kind: GitRepository
        name: flux-system
        namespace: flux-system
  values:
    nameOverride: platform-api
    image:
      repository: registry.lan.hummingbirdlabs.dev/platform-api
      tag: 1.0.12 # {"$imagepolicy": "image-automation:platform-api:tag"}
    ingress:
      enabled: true
      className: nginx
      hosts:
        - paths:
            - path: /
              pathType: Prefix
  valuesFrom:
    - kind: Secret
      name: platform-api-secret
      valuesKey: PLATFORM_API_INGRESS_HOST
      targetPath: ingress.hosts[0].host
