apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: actions-runner-controller-charts
  namespace: flux-system
spec:
  interval: 2h
  # ARC charts are hosted in GitHub Packages OCI registry
  type: oci
  url: oci://ghcr.io/actions/actions-runner-controller-charts
