apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - arc-controller-namespace.yaml
  - arc-controller-repository.yaml
  - arc-controller-release.yaml
  - arc-controller-scale-set-release.yaml
