apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - arc
  - metallb
  - ingress-nginx
  - image-automation
  - infisical
  - secrets-operator
  - infisical-bootstrap
  - traefik
