apiVersion: secrets.infisical.com/v1beta1
kind: InfisicalStaticSecret
metadata:
  name: homepage
  namespace: applications
spec:
  infisicalAuthRef:
    name: applications
    namespace: applications
  syncOptions:
    refreshInterval: 60s
  sources:
    - projectId: REPLACE_WITH_PROJECT_ID
      environmentSlug: prod
      secretPath: /
  targets:
    - name: homepage-secret
      namespace: applications
      kind: Secret
      creationPolicy: Owner
