apiVersion: v1
kind: PersistentVolume
metadata:
  name: data-postgres-0
  labels:
    app.kubernetes.io/part-of: postgres
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: postgres-manual
  local:
    path: /opt/postgres/data
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - k8s-node-1
