apiVersion: v1
kind: PersistentVolume
metadata:
  name: data-airflow-postgresql-0
  labels:
    app.kubernetes.io/part-of: airflow
    app.kubernetes.io/component: postgres
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: airflow-manual
  local:
    path: /opt/airflow/postgres
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - k8s-node-1
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: airflow-logs
  labels:
    app.kubernetes.io/part-of: airflow
    app.kubernetes.io/component: logs
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: airflow-manual
  local:
    path: /opt/airflow/logs
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - k8s-node-1
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: airflow-dags
  labels:
    app.kubernetes.io/part-of: airflow
    app.kubernetes.io/component: dags
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: airflow-manual
  local:
    path: /opt/airflow/dags
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - k8s-node-1
