apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: infisical
  namespace: infisical
spec:
  interval: 10m
  releaseName: infisical
  targetNamespace: infisical
  chart:
    spec:
      chart: infisical-standalone
      version: "1.4.x"
      sourceRef:
        kind: HelmRepository
        name: infisical
        namespace: flux-system
  values:
    infisical:
      replicaCount: 2
      image:
        repository: infisical/infisical
        tag: "v0.161.11"
        pullPolicy: IfNotPresent
      resources:
        requests:
          cpu: 350m
          memory: 512Mi
        limits:
          memory: 2Gi
      extraEnv:
        - name: ALLOW_INTERNAL_IP_CONNECTIONS
          value: "true"

    postgresql:
      enabled: true
      image:
        registry: mirror.gcr.io
        repository: bitnamilegacy/postgresql
      primary:
        persistence:
          enabled: true
          storageClass: infisical-manual
          size: 8Gi
          accessModes:
            - ReadWriteOnce

    redis:
      enabled: true
      image:
        registry: mirror.gcr.io
        repository: bitnamilegacy/redis
      master:
        persistence:
          enabled: true
          storageClass: infisical-manual
          size: 8Gi
          accessModes:
            - ReadWriteOnce

    ingress:
      enabled: true
      ingressClassName: nginx
      nginx:
        enabled: false
      hostName: infisical.lan.hummingbirdlabs.dev
