apiVersion: image.toolkit.fluxcd.io/v1
kind: ImageUpdateAutomation
metadata:
  name: flux-system
  namespace: image-automation
spec:
  interval: 1m0s
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  git:
    checkout:
      ref:
        branch: main
    commit:
      author:
        name: flux
        email: flux@hummingbirdlabs.dev
      messageTemplate: 'chore(images): auto update images'
    push:
      branch: main
  update:
    path: ./applications
    strategy: Setters
