apiVersion: v1
kind: PersistentVolume
metadata:
  name: data-traefik-0
  labels:
    app.kubernetes.io/part-of: traefik
spec:
  capacity:
    storage: 128Mi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: traefik-manual
  local:
    path: /opt/traefik/data
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - k8s-node-1
