apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: platform-api
  namespace: flux-system
spec:
  interval: 10m
  releaseName: platform-api
  targetNamespace: applications
  chart:
    spec:
      chart: ./packages/spring-boot-api
      reconcileStrategy: Revision
      sourceRef:
        kind: GitRepository
        name: flux-system
        namespace: flux-system
  values:
    nameOverride: platform-api
    image:
      repository: registry.lan.hummingbirdlabs.dev/platform-api
      tag: 1.0.9 # {"$imagepolicy": "image-automation:platform-api:tag"}
    ingress:
      enabled: true
      className: nginx
      hosts:
        - host: platform-api.lan.hummingbirdlabs.dev
          paths:
            - path: /
              pathType: Prefix
